### ISSUE TITLE
Cannot upload a post

### ISSUE THREAD

**Issue by Hosea987** [Amorem/FlutterSocial#1]
Hi there,i am new to flutter and have cloned this app in order to learn a few things and maybe move my other apps to flutter. Everything works fine but  i am unable to upload a post.
The progress bar just keeps going and going and there is no entry on firestore either. KIndly assist me with a remedy.

**Comment by vmodha** [comment]
You need to go into FIREBASE > Storage > Rules tab and make sure to remove the admin null text, so the line should read just 'allow read, write;'.

**Comment by Hosea987** [comment]
Issue sorted
